title: "My GitHub Page"
description: "个人主页"
url: ""                   # 部署后填写：https://你的用户名.github.io
baseurl: ""               # 如果是项目页填仓库名，例如 /my-repo；个人主页留空

theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除不需要编译的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github/
